export const types = {
  register: "REGISTER",
  login: "LOG_IN",
  logout: "LOG_OUT",
  followUser: "FOLLOW_USER",
  unfollowUser: "UNFOLLOW_USER",
  updateUsername: "UPDATE_USERNAME",
  updateUserProfileImage: "UPDATE_USER_PROFILE_IMAGE",
  updatePlaylist: "UPDATE_PLAYLIST",
  updateAlbum: "UPDATE_ALBUM",
  updateSong: "UPDATE_SONG",
  createPlaylist: "CREATE_PLAYLIST",
  togglePlaylistVisibility: "TOGGLE_PLAYLIST_VISIBILITY",
  deletePlaylist: "DELETE_PLAYLIST",
  deleteTrack: "DELETE_TRACK",
  deleteAlbum: "DELETE_ALBUM",
  changeCurrentTrack: "CHANGE_CURRENT_TRACK",
  toggleFollowAlbum: "FOLLOW_UNFOLLOW_ALBUM",
  initQueue: "INIT_QUEUE",
  createQueue: "CREATE_QUEUE",
  goNextPrevSong: "GO_TO_NEXT_SONG",
};
